# Site settings
title: A Camariana
description: ""
siteName: Camariana
keywords:
author: A Camariana
type: website
image: /assets/images/image.jpg
url: https://camariana.gm
permalink: /:categories/:title/

# Kramdown and Rouge
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge


# Global Configuration
source: src

# Sass Settings
sass:
  add_charset: true
  sass_dir: _sass
  style: :compressed

# Collections Settings
collections_dir: na_collectionul
collections:
  til:
    output: true
  case-studies:
    output: true
  projects:
    output: true
  fullstackopen:
    output: true  
  cssguidelines:
    output: true

# Contact & Social Details